version: '3.3'

services:
  db:
    image: postgres
  web:
    build: .
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  cli:
    build: .
    entrypoint: ./cli
    working_dir: /code/cli
    volumes:
      - .:/code
