#!/usr/bin/env python


import click


@click.group()
def cli():
    pass


@cli.group()
def conditions():
    pass


@conditions.command()
def list():
    click.echo('`cli conditions list` called')


if __name__ == '__main__':
    cli()
